kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-pv-volume
  labels:
    type: local
    name: influxdb-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
