GRANT ALL PRIVILEGES ON *.* TO 'mysql'@'%' IDENTIFIED BY 'mysql' WITH GRANT OPTION;

CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'wordpress'@'%' IDENTIFIED BY 'wordpress';
GRANT ALL PRIVILEGES ON wordpress.* TO "wordpress"@"%" with GRANT OPTION;
CREATE USER IF NOT EXISTS 'phpadmin'@'%' IDENTIFIED BY 'superCaliFragiliSticoESpiraLidoso';
GRANT ALL PRIVILEGES ON `phpmyadmin`.* TO 'phpadmin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;