apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: mysql-pv-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: ghcr.io/franzudev/my_sql:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-pv-storage
        ports:
        - name: db
          containerPort: 3306
      restartPolicy: Always
