#!/bin/sh

openrc default
openrc boot

rm /etc/my.cnf.d/mariadb-server.cnf
cp my.cnf /etc/my.cnf.d/mariadb-server.cnf

/etc/init.d/mariadb setup
/etc/init.d/mariadb start


echo "\ncreating database wordpress\n"
mysql < management.sql
mysql < wordpress.sql
mysql < phpmyadmin.sql
echo "\ndatabase wordpress created\n"
rm -f management.sql
rm -f wordpress.sql
rm -f phpmyadmin.sql

telegraf_init

./telegraf/usr/bin/telegraf --config /telegraf/etc/telegraf/telegraf.conf &

# automate mysql_secure_installation
mysql_secure

while mysqladmin ping --silent; do
    sleep 5
done