# # config file version
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    user: telegraf
    secureJsonData:
      password: $INFLUX_PASSWORD
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      httpMode: GET