apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: my_grafana:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 3000
      restartPolicy: Always