apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_key
spec:
  ports:
  - name: https
    port: 5000
    protocol: TCP
    targetPort: 443
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 127.0.0.240