apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  selector:
    app: ftps
  ports:
    - name: ftp
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv-min
      protocol: TCP
      port: 10098
      targetPort: 10098
    - name: pasv-mid
      protocol: TCP
      port: 10099
      targetPort: 10099
    - name: pasv-max
      protocol: TCP
      port: 10100
      targetPort: 10100
  type: LoadBalancer