apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  ports:
  # - name: http
  #   port: 5050
  #   protocol: TCP
  #   targetPort: 80
  - name: https
    port: 5050
    protocol: TCP
    targetPort: 443
  selector:
    app: wordpress
    tier: db