kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influx-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      type: local
      name: influxdb-pv-volume
