#!/bin/sh

php7-conf
openrc default
openrc boot

rc-service php-fpm7 start
rc-service php-fpm7 status
rc-service nginx status
rc-service nginx start

telegraf_init

./telegraf/usr/bin/telegraf --config /telegraf/etc/telegraf/telegraf.conf &

service_checker