apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services_key
spec:
  ports:
  - name: https
    port: 5050
    protocol: TCP
    targetPort: 443
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 127.0.0.240